#!/bin/sh

for f in war/lib/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done
CLASSPATH=.:lib:test:src:$CLASSPATH

if [ -z "$1" ]; then
   java -cp $CLASSPATH jline.ConsoleRunner clojure.lang.Repl
else
    java -cp $CLASSPATH clojure.lang.Script $1
fi
